apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-fs-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-fs-controller
  template:
    metadata:
      labels:
        app: csi-fs-controller
    spec:
      nodeName: tierra
      containers:
        - name: csi-driver
          image: karigar/csi-fs-driver:latest
          args:
            - "--endpoint=/csi/csi.sock"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: data-dir
              mountPath: /mnt/data
          securityContext:
            privileged: true

        - name: csi-provisioner
          image: registry.k8s.io/sig-storage/csi-provisioner:v3.6.0
          args:
            - "--csi-address=/csi/csi.sock"
            - "--v=5"
            - "--timeout=60s"
            - "--feature-gates=Topology=true"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi

      volumes:
        - name: socket-dir
          emptyDir: {}
        - name: data-dir
          hostPath:
            path: /mnt/data
            type: DirectoryOrCreate
