apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: csi.fs.local
spec:
  attachRequired: false
  podInfoOnMount: true
#  volumeLifecycleModes:
#    - Persistent
#  fsGroupPolicy: File
#  requiresRepublish: false