apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: csi-fs
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: csi-fs
  template:
    metadata:
      labels:
        app: csi-fs
    spec:
      containers:
        - name: csi-fs
          image: karigar/csi-fs-driver:latest
          args:
            - /csi-fs-driver
          volumeMounts:
            - mountPath: /var/lib/kubelet/plugins
              name: plugin-dir
            - mountPath: /mnt/data
              name: data-dir
      volumes:
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins
            type: DirectoryOrCreate
        - name: data-dir
          hostPath:
            path: /mnt/data
            type: DirectoryOrCreate
      #hostNetwork: true
      #dnsPolicy: ClusterFirstWithHostNet