# deploy/pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  nodeName: tierra
  containers:
    - name: app
      image: busybox
      command: ["/bin/sh", "-c"]
      args: ["echo hello > /data/test.txt && sleep 3600"]
      volumeMounts:
        - mountPath: /data
          name: simple-volume
  volumes:
    - name: simple-volume
      persistentVolumeClaim:
        claimName: simple-pvc
