apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  nodeName: tierra
  containers:
    - name: app
      image: busybox
      command: ["/bin/sh", "-c", "echo 'Hello, World!' >> /data/hello.txt  && sleep 3600"]
      volumeMounts:
        - name: test-vol
          mountPath: /data
  volumes:
    - name: test-vol
      persistentVolumeClaim:
        claimName: test-pvc