apiVersion: v1
kind: PersistentVolume
metadata:
  name: simple-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  csi:
    driver: csi.simple.local
    volumeHandle: simple-vol
    volumeAttributes:
      path: "/mnt/data/testvol"
